### ISSUE TITLE
Conveyance Report Missing Swale Photo

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#428]
@KCI-Ablowers @gerrykelly 

The feature reports in the viewer typically pull photos from the most recent inspection. We noticed these photos are missing from swale conveyance reports. Conveyance 0109000348 is an example. Pipe conveyance reports appear to still be working.

![image](https://user-images.githubusercontent.com/16919898/216426345-64082c63-639b-42d4-a433-af6dbbd8ab10.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
Only took about 7 years for someone to notice this never worked :-) ?
I fixed and prod and dev and tested (for one swale report in each) So, please do a quick test and also for a pipe to make sure nothing got messed up there.

I also made the same updates for the comparable code in the **multiReportStructConvey** task, but _I did not test_.

**Comment by cstevenson1** [comment]
@gerrykelly @KCI-Ablowers 

Confirmed it's working in dev and prod. I tried testing the multiReportStructConvey task though and could not get it to work in general. I tried restarting and still failed. The example below is for a pipe that I know previously worked. The following swales have the status set to be sent in nightly upload so they should hypothetically work:
0111319695, 0110326580, 0110110665, 0111319759, 0207332054

esriJobMessageTypeInformative: Submitted.
esriJobMessageTypeInformative: Executing...
esriJobMessageTypeInformative: Executing (multiReportStructConvey): multiReportStructConvey \\sparkssvm\DelDotPics\DelDOTstructure_conveyanceWOreportsForWebservice\Production WORK_ORDERS_MS4_Complete_TO_SEND "ASSET_NUM = '0112006869'" # #
esriJobMessageTypeInformative: Start Time: Mon Feb 6 14:42:29 2023
esriJobMessageTypeInformative: Executing (multiReportStructConvey): multiReportStructConvey \\sparkssvm\DelDotPics\DelDOTstructure_conveyanceWOreportsForWebservice\Production WORK_ORDERS_MS4_Complete_TO_SEND "ASSET_NUM = '0112006869'" # #
esriJobMessageTypeInformative: Start Time: Mon Feb 6 14:42:29 2023
esriJobMessageTypeInformative: Running script multiReportStructConvey...
esriJobMessageTypeInformative: Failed script multiReportStructConvey...
esriJobMessageTypeError: SyntaxError: invalid syntax (multiReportStructConvey.py, line 165)
esriJobMessageTypeError: Failed to execute (multiReportStructConvey).
esriJobMessageTypeInformative: Failed at Mon Feb 6 14:42:29 2023 (Elapsed Time: 0.10 seconds)
esriJobMessageTypeError: Failed to execute (multiReportStructConvey).
esriJobMessageTypeInformative: Failed at Mon Feb 6 14:42:29 2023 (Elapsed Time: 0.14 seconds)
esriJobMessageTypeError: Failed.

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
I fixed and tested in prod and dev
